#!/bin/bash
perl -pi -e 's/^Listen .*$/Listen 8889/;' /etc/apache2/listen.conf
perl -pi -e 's#^DocumentRoot .*$#DocumentRoot '`/bin/pwd`'/test-patches/#;' /etc/apache2/default-server.conf
cat <<EOF >>/etc/apache2/default-server.conf
<Directory "`/bin/pwd`/">
        Order allow,deny
        Allow from all
</Directory>
EOF
apache2ctl start
